#!/bin/bash

echo "🔧 Updating Supabase Configuration..."
echo ""
echo "Please provide your new Supabase project details:"

read -p "Enter your new Project Reference ID (from URL): " PROJECT_ID
read -p "Enter your new Project URL (https://[id].supabase.co): " PROJECT_URL
read -p "Enter your new anon public key: " ANON_KEY

echo ""
echo "📝 Updating .env file..."

# Update .env file
cat > .env << EOF
VITE_SUPABASE_PROJECT_ID="$PROJECT_ID"
VITE_SUPABASE_PUBLISHABLE_KEY="$ANON_KEY"
VITE_SUPABASE_URL="$PROJECT_URL"
EOF

echo "✅ .env file updated!"

# Update client.ts
echo "📝 Updating Supabase client..."
cat > src/integrations/supabase/client.ts << EOF
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "$PROJECT_URL";
const SUPABASE_PUBLISHABLE_KEY = "$ANON_KEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF

echo "✅ Supabase client updated!"
echo ""
echo "🎉 Configuration complete! Now deploy the Edge Function in Supabase Dashboard."