// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbjmiaoqovkylccgbfvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpiam1pYW9xb3ZreWxjY2diZnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODU3NzgsImV4cCI6MjA3MjU2MTc3OH0.lOdDi2JPMN9EBt2ksmMWipmaztifz2XJbOi7pxYNKXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
